# Generated by Django 4.1.8 on 2023-05-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOrder',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('item_price', models.IntegerField()),
                ('ordertime', models.TimeField(blank=True, db_column='OrderTime', null=True)),
                ('orderdate', models.DateField(blank=True, db_column='OrderDate', null=True)),
            ],
            options={
                'db_table': 'menu_order',
                'managed': False,
            },
        ),
    ]
